name: 'Build'
description: 'Build project'
inputs:
  platform:
    description: 'Platform name'
    required: true
  user:
    description: 'Username'
    required: true
  max_releases:
    description: 'Maximum number of old releases'
    required: false
    default: '5'
  infrastructure_dir:
    description: 'Infrastructure directory'
    required: false
    default: 'infrastructure'
outputs:
  version:
    description: 'Build version'
  build_dir:
    description: 'Build directory'
runs:
  using: 'node16'
  main: 'lib/index.js'
