name: Build
description: Build project

inputs:
  platform:
    description: Platform name
    required: true
  user:
    description: Username
    required: true
  max_releases:
    description: Maximum number of old releases
    required: false
    default: '5'
  infrastructure_dir:
    description: Infrastructure directory
    required: false
    default: infrastructure

outputs:
  version:
    description: Build version
    value: ${{ steps.core.outputs.version}}
  build_dir:
    description: Build directory
    value: ${{ steps.core.outputs.build_dir}}
  release_dir:
    description: Release directory
    value: ${{ steps.core.outputs.release_dir}}
  install_script:
    description: Install script
    value: ${{ steps.core.outputs.install_script}}

runs:
  using: composite
  steps:
    - name: Core build
      id: core
      uses: CrowdSoft-io/action-core@v1
      with:
        platform: ${{ inputs.platform }}
        user: ${{ inputs.user }}
        max_releases: ${{ inputs.max_releases }}
        infrastructure_dir: ${{ inputs.infrastructure_dir }}

    - uses: shivammathur/setup-php@v2
      if: steps.core.outputs.run_composer == true
      with:
        php-version: 8.1
    - name: Run composer
      if: steps.core.outputs.run_composer == true
      run: |
        APP_ENV=prod APP_DEBUG=0 composer install -n --no-dev
        tar -rf ${{ steps.core.outputs.build_dir}}/release.tar vendor
      shell: bash

    - run: gzip ${{ steps.core.outputs.build_dir}}/release.tar
      shell: bash
